# Sources configuration
# Format:
#   dir_name git  repo_url         branch
#   dir_name url  download_url     hash
#   dir_name file file_name        hash
#

bash          git  https://git.savannah.gnu.org/git/bash.git                            bash-5.3
busybox       git  https://git.busybox.net/busybox                                      1_37_0 # https://github.com/mirror/busybox.git
cacert        patch https://curl.se/ca/cacert-2026-03-19.pem                            sha256:b6e66569cc3d438dd5abe514d0df50005d570bfc96c14dca8f768d020cb96171
curl          git  https://github.com/curl/curl.git                                     curl-8_19_0
dropbear      git  https://github.com/mkj/dropbear.git                                  master
git           git  https://github.com/git/git.git                                       v2.53.0
gnulib        git  git://git.git.savannah.gnu.org/gnulib.git                            master # https://github.com/coreutils/gnulib.git https://git.savannah.gnu.org/git/gnulib.git git://git.sv.gnu.org/gnulib.git https://gitweb.git.savannah.gnu.org/gitweb/?p=gnulib.git git://git.savannah.gnu.org/gnulib.git
linux         git  https://github.com/torvalds/linux.git                                v7.0
memtest86plus git  https://github.com/memtest86plus/memtest86plus.git                   v8.00
microwindows  git  https://github.com/ghaerr/microwindows.git                           master
musl          git  git://git.musl-libc.org/musl                                         v1.2.5 # https://git.musl-libc.org/cgit/musl
nano          git  https://github.com/madnight/nano.git                                 master # https://git.savannah.gnu.org/git/nano.git
syslinux      git  https://salsa.debian.org/images-team/syslinux.git                    debian/master # git://repo.or.cz/syslinux.git
toybox        git  https://github.com/landley/toybox.git                                0.8.13
wlroots       git  https://gitlab.freedesktop.org/wlroots/wlroots.git                   0.18.3
