linux         git  https://github.com/torvalds/linux.git                                v7.0
busybox       git  https://git.busybox.net/busybox                                      1_37_0 # https://github.com/mirror/busybox.git
syslinux      git  https://salsa.debian.org/images-team/syslinux.git                    debian/master # git://repo.or.cz/syslinux.git
memtest86plus git  https://github.com/memtest86plus/memtest86plus.git                   v8.00
microwindows  git  https://github.com/ghaerr/microwindows.git                           master
dropbear      git  https://github.com/mkj/dropbear.git                                  master
nano          git  https://github.com/madnight/nano.git                                 master # https://git.savannah.gnu.org/git/nano.git
curl          git  https://github.com/curl/curl.git                                     curl-8_18_0
gnulib        git  git://git.git.savannah.gnu.org/gnulib.git                            master
